GET http://localhost:5000/products

###
GET http://localhost:5000/products/3

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 5",
    "price": 2000
}

###
PATCH  http://localhost:5000/products/16
Content-Type: application/json

{
    "name": "Product 4 updated",
    "price": 4000
}

###
DELETE http://localhost:5000/products/6